version: '3'
services:
  client:
    container_name: postgressers
    build: ./client
    image: debug_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  server:
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./server
        target: /code
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=
      - DB_CONNECTION=
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api 
        target: /code
    command: bash -c "npm install && npm start"


  db:
    image: mongo:latest
    volumes:
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=postgressers
      - MONGO_INITDB_DATABASE=habitat
      - MONGO_INITDB_ROOT_PASSWORD=jakcika123
volumes:
  dbdata:

